export const theme = {
  colors: {
    background: '#fff7ff',
    error: '#ba1a1a',
    error_container: '#ffdad6',
    on_error: '#ffffff',
    on_error_container: '#93000a',
    primary: '#460045',
    primary_container: '#631660',
    on_primary: '#ffffff',
    on_primary_container: '#dd83d2',
    secondary: '#9b2f96',
    secondary_container: '#fc85ef',
    on_secondary: '#ffffff',
    surface: '#fff7ff',
    surface_container: '#f4ebf6',
    surface_container_high: '#eee5f0',
    surface_container_lowest: '#ffffff',
    on_surface: '#1e1a22',
    on_surface_variant: '#50434d',
    outline: '#82737d',
    outline_variant: '#d4c1cd',
  },
  fonts: {
    light: 'Inter_300Light',
    regular: 'Inter_400Regular',
    medium: 'Inter_500Medium',
    bold: 'Inter_700Bold',
    black: 'Inter_900Black',
  },
};
