directories:
  output: release
  buildResources: build
appId: com.pontofacil.app
productName: Ponto Fácil
copyright: Copyright © 2026 Ponto Fácil
forceCodeSigning: false
asar: true
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - node_modules/electron-store/**/*
      - '!node_modules/.cache/**/*'
extraMetadata:
  main: electron/main.js
win:
  icon: build/icon.png
  target:
    - target: nsis
      arch:
        - x64
    - target: portable
      arch:
        - x64
  artifactName: ${productName}-${version}-Setup.${ext}
portable:
  artifactName: ${productName}-${version}-Portable.${ext}
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  installerIcon: build/icon.png
  uninstallerIcon: build/icon.png
  shortcutName: Ponto Fácil
  createDesktopShortcut: true
  createStartMenuShortcut: true
  installerHeaderIcon: build/icon.png
publish: null
electronVersion: 41.1.0
